export const SEARCH_FOR_USER = 'SEARCH_FOR_USER';
export const HANDEL_AUTH = 'HANDEL_AUTH';

export const SWITCH_CAMERA = 'SWITCH_CAMERA';
export const SWITCH_STOP_CAMERA = 'SWITCH_STOP_CAMERA';
export const SWITCH_MUTE_MIC = 'SWITCH_MUTE_MIC';
export const END_CALL = 'END_CALL';
export const CALL_STATUS = 'CALL_STATUS';

export const SET_CALLER_DISPLAY_NAME = 'SET_CALLER_DISPLAY_NAME';
export const HANDEL_LOCAL_VIDEO_STREAM_ID = 'HANDEL_LOCAL_VIDEO_STREAM_ID';
export const HANDEL_REMOTE_VIDEO_STREAM_ID = 'HANDEL_REMOTE_VIDEO_STREAM_ID';
